name: Comment Commands
on:
  issue_comment:
    types: [ created ]

jobs:
  wpiformat:
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '\wpiformat')
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2022-20.04
    steps:
      - name: React Rocket
        uses: actions/github-script@v4
        with:
          script: |
            const {owner, repo} = context.issue
            github.reactions.createForIssueComment({
              owner,
              repo,
              comment_id: context.payload.comment.id,
              content: "rocket",
            });
      - uses: actions/checkout@v2
      - name: Fetch all history and metadata
        run: |
          git fetch --prune --unshallow
          git checkout -b pr
          git branch -f main origin/main
      - name: Checkout PR
        run: gh pr checkout $NUMBER
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          NUMBER: ${{ github.event.issue.number }}
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install clang-format
        run: |
          sudo sh -c "echo 'deb http://archive.ubuntu.com/ubuntu/ $(lsb_release -cs)-proposed restricted main multiverse universe' >> /etc/apt/sources.list.d/proposed-repositories.list"
          sudo apt-get update -q
          sudo apt-get install -y clang-format-12
      - name: Install wpiformat
        run: pip3 install wpiformat
      - name: Run wpiformat
        run: wpiformat -clang 12
      - name: Commit
        run: |
          # Set credentials
          git config user.name github-actions
          git config user.email github-actions@github.com
          git diff --name-only --diff-filter=Md | xargs -I{} git add {}
          # Commit
          git commit -m "Autofix RLIs"
          git push
